listeners:
  home:
    host: "0.0.0.0"
    port: 5521
  world2:
    host: "0.0.0.0"
    port: 5522

default: "home"

servers:
  home:
    host: "127.0.0.1"
    port: 5520
  world2:
    host: "127.0.0.1"
    port: 5524
